
server:
  port:
    8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          searchLocations: file:///C:/DEV_WorkSpace/Rep_IntelliJ/dio/config-repo
        #git:
          #uri: https://github.com/oswaldoneto/dio-experts-config.git
